@baseUrl = http://localhost:5000
@testEmail = verification-test@test.local
@verificationToken = PASTE_TOKEN_FROM_MAILPIT

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "{{testEmail}}",
  "password": "123456"
}

### Verify email
POST {{baseUrl}}/api/auth/verify-email
Content-Type: application/json

{
  "token": "{{verificationToken}}"
}

### Resend verification email
POST {{baseUrl}}/api/auth/resend-verification
Content-Type: application/json

{
  "email": "{{testEmail}}"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "123456",
  "rememberMe": true
}

### Me
GET {{baseUrl}}/api/auth/me

### Dashboard
GET {{baseUrl}}/api/dashboard

### Admin
GET {{baseUrl}}/api/admin

### Logout
POST {{baseUrl}}/api/auth/logout
